server:
  port: 8081

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group-id
      enable-auto-commit: false
      auto-offset-reset: earliest

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
